# Generated by Django 3.2.12 on 2022-02-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_appointment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
    ]
