# Generated by Django 3.2.9 on 2022-02-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('canceled', 'canceled')], max_length=20, null=True),
        ),
    ]
